name: pr

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install lint utilities
        run: |
          python -m pip install pre-commit
          pre-commit install-hooks
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41.0.0
      - name: Lint modified files
        run: pre-commit run --files ${{ steps.changed-files.outputs.all_changed_files }}
